-- USA Security Connect - Postgres schema.
--
-- Runs identically on Neon (production) and PGlite (local dev, tests, CI),
-- so there is one SQL dialect to reason about rather than two.
--
-- Conventions:
--   * identity columns are BY DEFAULT, so the seed can supply explicit ids
--   * anything that was an INTEGER 0/1 flag in SQLite is a real boolean
--   * event timestamps are timestamptz; calendar fields (hire date, licence
--     expiry) are plain date, because they are not moments in time
--   * money is stored in whole cents as integer, never floating point

CREATE TABLE IF NOT EXISTS sites (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text NOT NULL,
  client_name   text,
  address       text,
  city          text,
  state         text DEFAULT 'FL',
  postal_code   text,
  latitude      double precision,
  longitude     double precision,
  timezone      text DEFAULT 'America/New_York',
  contact_name  text,
  contact_phone text,
  contact_email text,
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS posts (
  id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id               integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name                  text NOT NULL,
  post_code             text,
  instructions          text,
  address               text,
  latitude              double precision,
  longitude             double precision,
  geofence_radius_m     integer DEFAULT 150,
  check_in_interval_min integer DEFAULT 60,
  requires_gps          boolean NOT NULL DEFAULT true,
  armed                 boolean NOT NULL DEFAULT false,
  bill_rate_cents       integer,
  active                boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_posts_site ON posts(site_id);

CREATE TABLE IF NOT EXISTS users (
  id                           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_code                text NOT NULL UNIQUE,
  first_name                   text NOT NULL,
  last_name                    text NOT NULL,
  email                        text,
  phone                        text,
  role                         text NOT NULL DEFAULT 'officer',
  pin_hash                     text,
  pin_salt                     text,
  pin_set_at                   timestamptz,
  must_change_pin              boolean NOT NULL DEFAULT true,
  status                       text NOT NULL DEFAULT 'active',
  hire_date                    date,
  license_number               text,
  license_type                 text,
  license_expires_on           date,
  emergency_contact_name       text,
  emergency_contact_phone      text,
  emergency_contact_relation   text,
  default_site_id              integer REFERENCES sites(id) ON DELETE SET NULL,

  -- employment classification and pay
  employment_type              text NOT NULL DEFAULT 'w2',
  pay_type                     text NOT NULL DEFAULT 'hourly',
  exempt                       boolean NOT NULL DEFAULT false,
  overtime_multiplier          double precision NOT NULL DEFAULT 1.5,
  pay_rate_cents               integer,
  salary_cents                 integer,
  bill_rate_cents              integer,

  -- 1099 contractor paperwork
  business_name                text,
  tax_id_last4                 text,
  w9_on_file                   boolean NOT NULL DEFAULT false,
  contractor_agreement_on_file boolean NOT NULL DEFAULT false,
  insurance_expires_on         date,

  -- profile
  address_line1                text,
  address_line2                text,
  city                         text,
  state                        text,
  postal_code                  text,
  uniform_size                 text,
  avatar_filename              text,

  failed_attempts              integer NOT NULL DEFAULT 0,
  locked_until                 timestamptz,
  last_login_at                timestamptz,
  notes                        text,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_code ON users(employee_code);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

CREATE TABLE IF NOT EXISTS shifts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer REFERENCES users(id) ON DELETE SET NULL,
  post_id         integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  starts_at       timestamptz NOT NULL,
  ends_at         timestamptz NOT NULL,
  status          text NOT NULL DEFAULT 'scheduled',
  notes           text,
  bill_rate_cents integer,
  is_open         boolean NOT NULL DEFAULT false,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_shifts_user_time ON shifts(user_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_shifts_time ON shifts(starts_at);
CREATE INDEX IF NOT EXISTS idx_shifts_open ON shifts(is_open, starts_at);

CREATE TABLE IF NOT EXISTS time_entries (
  id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id               integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shift_id              integer REFERENCES shifts(id) ON DELETE SET NULL,
  post_id               integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  clock_in_at           timestamptz NOT NULL,
  clock_in_lat          double precision,
  clock_in_lng          double precision,
  clock_in_accuracy     double precision,
  clock_in_geofence     text,
  clock_in_distance_m   integer,
  clock_out_at          timestamptz,
  clock_out_lat         double precision,
  clock_out_lng         double precision,
  clock_out_accuracy    double precision,
  clock_out_geofence    text,
  method                text NOT NULL DEFAULT 'gps',
  device_id             text,
  minutes_worked        integer,
  late_minutes          integer DEFAULT 0,
  unpaid_break_minutes  integer NOT NULL DEFAULT 0,
  auto_closed           boolean NOT NULL DEFAULT false,
  adjusted_by           integer REFERENCES users(id) ON DELETE SET NULL,
  adjustment_reason     text,
  original_clock_in_at  timestamptz,
  original_clock_out_at timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_entries_user ON time_entries(user_id, clock_in_at);
CREATE INDEX IF NOT EXISTS idx_entries_open ON time_entries(clock_out_at);

CREATE TABLE IF NOT EXISTS status_checks (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  time_entry_id  integer NOT NULL REFERENCES time_entries(id) ON DELETE CASCADE,
  user_id        integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  due_at         timestamptz NOT NULL,
  window_minutes integer NOT NULL DEFAULT 10,
  responded_at   timestamptz,
  notified_at    timestamptz,
  status         text NOT NULL DEFAULT 'pending',
  latitude       double precision,
  longitude      double precision,
  note           text
);
CREATE INDEX IF NOT EXISTS idx_checks_entry ON status_checks(time_entry_id, due_at);
CREATE INDEX IF NOT EXISTS idx_checks_pending ON status_checks(status, due_at);

CREATE TABLE IF NOT EXISTS incidents (
  id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ref_number           text NOT NULL UNIQUE,
  user_id              integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id              integer REFERENCES sites(id) ON DELETE SET NULL,
  post_id              integer REFERENCES posts(id) ON DELETE SET NULL,
  tour_run_id          integer,
  checkpoint_id        integer,
  officer_name         text,
  callback_number      text,
  category             text,
  severity             text NOT NULL DEFAULT 'low',
  occurred_at          timestamptz NOT NULL,
  location_text        text,
  what_happened        text NOT NULL,
  resolution           text,
  other_details        text,
  people_involved      text,
  people_notified      text,
  police_notified      boolean NOT NULL DEFAULT false,
  police_report_number text,
  cost_recovery_cents  integer,
  status               text NOT NULL DEFAULT 'submitted',
  reviewed_by          integer REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at          timestamptz,
  review_notes         text,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_incidents_time ON incidents(occurred_at);
CREATE INDEX IF NOT EXISTS idx_incidents_site ON incidents(site_id, occurred_at);

CREATE TABLE IF NOT EXISTS incident_photos (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  incident_id   integer NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  filename      text NOT NULL,
  -- Set when the file lives in object storage rather than on local disk.
  storage_url   text,
  original_name text,
  mime_type     text,
  size_bytes    integer,
  caption       text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supervisor_visits (
  id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supervisor_id        integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  officer_id           integer REFERENCES users(id) ON DELETE SET NULL,
  site_id              integer REFERENCES sites(id) ON DELETE SET NULL,
  post_id              integer REFERENCES posts(id) ON DELETE SET NULL,
  visited_at           timestamptz NOT NULL,
  uniform_ok           boolean,
  post_orders_reviewed boolean,
  equipment_ok         boolean,
  site_secure          boolean,
  rating               integer,
  notes                text,
  latitude             double precision,
  longitude            double precision,
  created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tours (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name             text NOT NULL,
  description      text,
  expected_minutes integer,
  active           boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checkpoints (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_id      integer NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  name         text NOT NULL,
  sequence     integer NOT NULL DEFAULT 0,
  nfc_tag_id   text,
  qr_code      text,
  latitude     double precision,
  longitude    double precision,
  instructions text,
  required     boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_checkpoints_tour ON checkpoints(tour_id, sequence);

CREATE TABLE IF NOT EXISTS checkpoint_tasks (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  checkpoint_id integer NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
  label         text NOT NULL,
  sequence      integer NOT NULL DEFAULT 0,
  required      boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS tour_runs (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_id       integer NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id integer REFERENCES time_entries(id) ON DELETE SET NULL,
  started_at    timestamptz NOT NULL,
  completed_at  timestamptz,
  status        text NOT NULL DEFAULT 'in_progress'
);
CREATE INDEX IF NOT EXISTS idx_runs_user ON tour_runs(user_id, started_at);

CREATE TABLE IF NOT EXISTS tour_run_checkpoints (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_run_id   integer NOT NULL REFERENCES tour_runs(id) ON DELETE CASCADE,
  checkpoint_id integer NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
  status        text NOT NULL DEFAULT 'pending',
  scanned_at    timestamptz,
  method        text,
  latitude      double precision,
  longitude     double precision,
  skip_reason   text
);

CREATE TABLE IF NOT EXISTS tour_run_tasks (
  id                     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_run_checkpoint_id integer NOT NULL REFERENCES tour_run_checkpoints(id) ON DELETE CASCADE,
  checkpoint_task_id     integer NOT NULL REFERENCES checkpoint_tasks(id) ON DELETE CASCADE,
  status                 text NOT NULL DEFAULT 'pending',
  note                   text,
  completed_at           timestamptz
);

CREATE TABLE IF NOT EXISTS broadcasts (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title            text NOT NULL,
  body             text NOT NULL,
  priority         text NOT NULL DEFAULT 'normal',
  requires_ack     boolean NOT NULL DEFAULT false,
  audience_role    text,
  audience_site_id integer REFERENCES sites(id) ON DELETE SET NULL,
  published_at     timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz,
  created_by       integer REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS broadcast_receipts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  broadcast_id    integer NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at         timestamptz,
  acknowledged_at timestamptz,
  UNIQUE (broadcast_id, user_id)
);

CREATE TABLE IF NOT EXISTS trainings (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title            text NOT NULL,
  description      text,
  video_url        text,
  duration_seconds integer NOT NULL DEFAULT 0,
  required         boolean NOT NULL DEFAULT false,
  due_at           timestamptz,
  audience_role    text,
  created_by       integer REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS training_progress (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  training_id     integer NOT NULL REFERENCES trainings(id) ON DELETE CASCADE,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seconds_watched integer NOT NULL DEFAULT 0,
  completed_at    timestamptz,
  UNIQUE (training_id, user_id)
);

CREATE TABLE IF NOT EXISTS threads (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject         text,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz
);

CREATE TABLE IF NOT EXISTS thread_participants (
  thread_id    integer NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_at timestamptz,
  PRIMARY KEY (thread_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  thread_id integer NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body      text NOT NULL,
  sent_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id, sent_at);

CREATE TABLE IF NOT EXISTS flags (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type            text NOT NULL,
  severity        text NOT NULL DEFAULT 'warning',
  occurred_at     timestamptz NOT NULL,
  ref_type        text,
  ref_id          integer,
  detail          jsonb,
  notified_at     timestamptz,
  resolved_at     timestamptz,
  resolved_by     integer REFERENCES users(id) ON DELETE SET NULL,
  resolution_note text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (type, ref_type, ref_id)
);
CREATE INDEX IF NOT EXISTS idx_flags_open ON flags(resolved_at, occurred_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_id   integer REFERENCES users(id) ON DELETE SET NULL,
  action     text NOT NULL,
  entity     text,
  entity_id  integer,
  detail     text,
  ip         text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_log(created_at DESC);

CREATE TABLE IF NOT EXISTS device_tokens (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token        text NOT NULL UNIQUE,
  platform     text,
  device_id    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_device_user ON device_tokens(user_id);

CREATE TABLE IF NOT EXISTS certifications (
  id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id           integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type              text NOT NULL,
  number            text,
  issuing_authority text,
  issued_on         date,
  expires_on        date,
  document_filename text,
  verified_by       integer REFERENCES users(id) ON DELETE SET NULL,
  verified_at       timestamptz,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_certs_user ON certifications(user_id);
CREATE INDEX IF NOT EXISTS idx_certs_expiry ON certifications(expires_on);

CREATE TABLE IF NOT EXISTS availability (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  weekday    integer NOT NULL,
  start_time text NOT NULL DEFAULT '00:00',
  end_time   text NOT NULL DEFAULT '23:59',
  available  boolean NOT NULL DEFAULT true,
  note       text,
  UNIQUE (user_id, weekday)
);

CREATE TABLE IF NOT EXISTS time_off_requests (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text NOT NULL DEFAULT 'vacation',
  starts_on     date NOT NULL,
  ends_on       date NOT NULL,
  reason        text,
  status        text NOT NULL DEFAULT 'pending',
  decided_by    integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at    timestamptz,
  decision_note text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_timeoff_user ON time_off_requests(user_id, starts_on);
CREATE INDEX IF NOT EXISTS idx_timeoff_status ON time_off_requests(status);

CREATE TABLE IF NOT EXISTS breaks (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  time_entry_id integer NOT NULL REFERENCES time_entries(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text NOT NULL DEFAULT 'meal',
  paid          boolean NOT NULL DEFAULT false,
  started_at    timestamptz NOT NULL,
  ended_at      timestamptz,
  minutes       integer,
  start_lat     double precision,
  start_lng     double precision
);
CREATE INDEX IF NOT EXISTS idx_breaks_entry ON breaks(time_entry_id);

CREATE TABLE IF NOT EXISTS panic_alerts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id   integer REFERENCES time_entries(id) ON DELETE SET NULL,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  triggered_at    timestamptz NOT NULL DEFAULT now(),
  latitude        double precision,
  longitude       double precision,
  accuracy        double precision,
  note            text,
  status          text NOT NULL DEFAULT 'active',
  acknowledged_by integer REFERENCES users(id) ON DELETE SET NULL,
  acknowledged_at timestamptz,
  resolved_at     timestamptz,
  resolution_note text
);
CREATE INDEX IF NOT EXISTS idx_panic_status ON panic_alerts(status, triggered_at);

-- Officers claiming open shifts, and swapping assigned ones between each other.
CREATE TABLE IF NOT EXISTS shift_requests (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind           text NOT NULL,                   -- 'claim' | 'swap' | 'drop'
  shift_id       integer NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  requested_by   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- For a swap: who is being asked to take it, and what they give back.
  target_user_id integer REFERENCES users(id) ON DELETE CASCADE,
  offered_shift_id integer REFERENCES shifts(id) ON DELETE CASCADE,
  note           text,
  status         text NOT NULL DEFAULT 'pending', -- pending|accepted|declined|approved|denied|cancelled
  decided_by     integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at     timestamptz,
  decision_note  text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_shift_requests_status ON shift_requests(status, created_at);
CREATE INDEX IF NOT EXISTS idx_shift_requests_shift ON shift_requests(shift_id);

-- Read-only client contacts. Scoped to their own sites, and they never see
-- pay, margin or anything about another client.
CREATE TABLE IF NOT EXISTS client_users (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email           text NOT NULL UNIQUE,
  name            text NOT NULL,
  company         text,
  password_hash   text,
  password_salt   text,
  status          text NOT NULL DEFAULT 'active',
  last_login_at   timestamptz,
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until    timestamptz,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS client_sites (
  client_user_id integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  site_id        integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  PRIMARY KEY (client_user_id, site_id)
);

CREATE TABLE IF NOT EXISTS invoices (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number        text NOT NULL UNIQUE,
  site_id       integer NOT NULL REFERENCES sites(id) ON DELETE RESTRICT,
  period_start  date NOT NULL,
  period_end    date NOT NULL,
  status        text NOT NULL DEFAULT 'draft',   -- draft|sent|paid|void
  subtotal_cents integer NOT NULL DEFAULT 0,
  tax_cents      integer NOT NULL DEFAULT 0,
  total_cents    integer NOT NULL DEFAULT 0,
  -- What the same hours cost us, so margin survives on the record.
  cost_cents     integer NOT NULL DEFAULT 0,
  notes         text,
  issued_at     timestamptz,
  due_on        date,
  paid_at       timestamptz,
  created_by    integer REFERENCES users(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invoices_site ON invoices(site_id, period_start);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id      integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  description     text NOT NULL,
  minutes         integer NOT NULL DEFAULT 0,
  rate_cents      integer NOT NULL DEFAULT 0,
  amount_cents    integer NOT NULL DEFAULT 0,
  cost_cents      integer NOT NULL DEFAULT 0,
  sequence        integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_invoice_lines ON invoice_lines(invoice_id, sequence);
