/**
 * The database schema, as one idempotent script.
 *
 * This used to be schema.sql, read at runtime with fs.readFileSync. That works
 * on a long-running host and fails on a serverless one: the bundler traces
 * imports, not computed file paths, so the .sql file was never shipped and
 * every request died on ENOENT before it reached a single route. Inlining it
 * makes the schema a module like any other - traced, bundled, and identical on
 * both surfaces, which is the whole point of sharing app.js between them.
 *
 * The inline sql marker before the literal is what editors and Prettier look
 * for to syntax highlight and format it.
 */

export const SCHEMA_SQL = /* sql */ `
-- USA Security Connect - Postgres schema.
--
-- Runs identically on Neon (production) and PGlite (local dev, tests, CI),
-- so there is one SQL dialect to reason about rather than two.
--
-- Conventions:
--   * identity columns are BY DEFAULT, so the seed can supply explicit ids
--   * anything that was an INTEGER 0/1 flag in SQLite is a real boolean
--   * event timestamps are timestamptz; calendar fields (hire date, licence
--     expiry) are plain date, because they are not moments in time
--   * money is stored in whole cents as integer, never floating point

CREATE TABLE IF NOT EXISTS sites (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          text NOT NULL,
  client_name   text,
  address       text,
  city          text,
  state         text DEFAULT 'FL',
  postal_code   text,
  latitude      double precision,
  longitude     double precision,
  timezone      text DEFAULT 'America/New_York',
  contact_name  text,
  contact_phone text,
  contact_email text,
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS posts (
  id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id               integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name                  text NOT NULL,
  post_code             text,
  instructions          text,
  address               text,
  latitude              double precision,
  longitude             double precision,
  geofence_radius_m     integer DEFAULT 150,
  check_in_interval_min integer DEFAULT 60,
  requires_gps          boolean NOT NULL DEFAULT true,
  armed                 boolean NOT NULL DEFAULT false,
  bill_rate_cents       integer,
  active                boolean NOT NULL DEFAULT true,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_posts_site ON posts(site_id);

CREATE TABLE IF NOT EXISTS users (
  id                           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_code                text NOT NULL UNIQUE,
  first_name                   text NOT NULL,
  last_name                    text NOT NULL,
  email                        text,
  phone                        text,
  role                         text NOT NULL DEFAULT 'officer',
  pin_hash                     text,
  pin_salt                     text,
  pin_set_at                   timestamptz,
  must_change_pin              boolean NOT NULL DEFAULT true,
  status                       text NOT NULL DEFAULT 'active',
  hire_date                    date,
  license_number               text,
  license_type                 text,
  license_expires_on           date,
  emergency_contact_name       text,
  emergency_contact_phone      text,
  emergency_contact_relation   text,
  default_site_id              integer REFERENCES sites(id) ON DELETE SET NULL,

  -- employment classification and pay
  employment_type              text NOT NULL DEFAULT 'w2',
  pay_type                     text NOT NULL DEFAULT 'hourly',
  exempt                       boolean NOT NULL DEFAULT false,
  overtime_multiplier          double precision NOT NULL DEFAULT 1.5,
  pay_rate_cents               integer,
  salary_cents                 integer,
  bill_rate_cents              integer,

  -- 1099 contractor paperwork
  business_name                text,
  tax_id_last4                 text,
  w9_on_file                   boolean NOT NULL DEFAULT false,
  contractor_agreement_on_file boolean NOT NULL DEFAULT false,
  insurance_expires_on         date,

  -- profile
  address_line1                text,
  address_line2                text,
  city                         text,
  state                        text,
  postal_code                  text,
  uniform_size                 text,
  avatar_filename              text,

  failed_attempts              integer NOT NULL DEFAULT 0,
  locked_until                 timestamptz,
  last_login_at                timestamptz,
  notes                        text,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_code ON users(employee_code);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);

CREATE TABLE IF NOT EXISTS shifts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer REFERENCES users(id) ON DELETE SET NULL,
  post_id         integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  starts_at       timestamptz NOT NULL,
  ends_at         timestamptz NOT NULL,
  status          text NOT NULL DEFAULT 'scheduled',
  notes           text,
  bill_rate_cents integer,
  is_open         boolean NOT NULL DEFAULT false,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_shifts_user_time ON shifts(user_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_shifts_time ON shifts(starts_at);
CREATE INDEX IF NOT EXISTS idx_shifts_open ON shifts(is_open, starts_at);

CREATE TABLE IF NOT EXISTS time_entries (
  id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id               integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  shift_id              integer REFERENCES shifts(id) ON DELETE SET NULL,
  post_id               integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  clock_in_at           timestamptz NOT NULL,
  clock_in_lat          double precision,
  clock_in_lng          double precision,
  clock_in_accuracy     double precision,
  clock_in_geofence     text,
  clock_in_distance_m   integer,
  clock_out_at          timestamptz,
  clock_out_lat         double precision,
  clock_out_lng         double precision,
  clock_out_accuracy    double precision,
  clock_out_geofence    text,
  method                text NOT NULL DEFAULT 'gps',
  device_id             text,
  minutes_worked        integer,
  late_minutes          integer DEFAULT 0,
  unpaid_break_minutes  integer NOT NULL DEFAULT 0,
  auto_closed           boolean NOT NULL DEFAULT false,
  adjusted_by           integer REFERENCES users(id) ON DELETE SET NULL,
  adjustment_reason     text,
  original_clock_in_at  timestamptz,
  original_clock_out_at timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_entries_user ON time_entries(user_id, clock_in_at);
CREATE INDEX IF NOT EXISTS idx_entries_open ON time_entries(clock_out_at);

CREATE TABLE IF NOT EXISTS status_checks (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  time_entry_id  integer NOT NULL REFERENCES time_entries(id) ON DELETE CASCADE,
  user_id        integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  due_at         timestamptz NOT NULL,
  window_minutes integer NOT NULL DEFAULT 10,
  responded_at   timestamptz,
  notified_at    timestamptz,
  status         text NOT NULL DEFAULT 'pending',
  latitude       double precision,
  longitude      double precision,
  note           text
);
CREATE INDEX IF NOT EXISTS idx_checks_entry ON status_checks(time_entry_id, due_at);
CREATE INDEX IF NOT EXISTS idx_checks_pending ON status_checks(status, due_at);

CREATE TABLE IF NOT EXISTS incidents (
  id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ref_number           text NOT NULL UNIQUE,
  user_id              integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id              integer REFERENCES sites(id) ON DELETE SET NULL,
  post_id              integer REFERENCES posts(id) ON DELETE SET NULL,
  tour_run_id          integer,
  checkpoint_id        integer,
  officer_name         text,
  callback_number      text,
  category             text,
  severity             text NOT NULL DEFAULT 'low',
  occurred_at          timestamptz NOT NULL,
  location_text        text,
  what_happened        text NOT NULL,
  resolution           text,
  other_details        text,
  people_involved      text,
  people_notified      text,
  police_notified      boolean NOT NULL DEFAULT false,
  police_report_number text,
  cost_recovery_cents  integer,
  status               text NOT NULL DEFAULT 'submitted',
  reviewed_by          integer REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at          timestamptz,
  review_notes         text,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_incidents_time ON incidents(occurred_at);
CREATE INDEX IF NOT EXISTS idx_incidents_site ON incidents(site_id, occurred_at);

CREATE TABLE IF NOT EXISTS incident_photos (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  incident_id   integer NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  filename      text NOT NULL,
  -- Set when the file lives in object storage rather than on local disk.
  storage_url   text,
  original_name text,
  mime_type     text,
  size_bytes    integer,
  caption       text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS supervisor_visits (
  id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supervisor_id        integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  officer_id           integer REFERENCES users(id) ON DELETE SET NULL,
  site_id              integer REFERENCES sites(id) ON DELETE SET NULL,
  post_id              integer REFERENCES posts(id) ON DELETE SET NULL,
  visited_at           timestamptz NOT NULL,
  uniform_ok           boolean,
  post_orders_reviewed boolean,
  equipment_ok         boolean,
  site_secure          boolean,
  rating               integer,
  notes                text,
  latitude             double precision,
  longitude            double precision,
  created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tours (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name             text NOT NULL,
  description      text,
  expected_minutes integer,
  active           boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checkpoints (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_id      integer NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  name         text NOT NULL,
  sequence     integer NOT NULL DEFAULT 0,
  nfc_tag_id   text,
  qr_code      text,
  latitude     double precision,
  longitude    double precision,
  instructions text,
  required     boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_checkpoints_tour ON checkpoints(tour_id, sequence);

CREATE TABLE IF NOT EXISTS checkpoint_tasks (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  checkpoint_id integer NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
  label         text NOT NULL,
  sequence      integer NOT NULL DEFAULT 0,
  required      boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS tour_runs (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_id       integer NOT NULL REFERENCES tours(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id integer REFERENCES time_entries(id) ON DELETE SET NULL,
  started_at    timestamptz NOT NULL,
  completed_at  timestamptz,
  status        text NOT NULL DEFAULT 'in_progress'
);
CREATE INDEX IF NOT EXISTS idx_runs_user ON tour_runs(user_id, started_at);

CREATE TABLE IF NOT EXISTS tour_run_checkpoints (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_run_id   integer NOT NULL REFERENCES tour_runs(id) ON DELETE CASCADE,
  checkpoint_id integer NOT NULL REFERENCES checkpoints(id) ON DELETE CASCADE,
  status        text NOT NULL DEFAULT 'pending',
  scanned_at    timestamptz,
  method        text,
  latitude      double precision,
  longitude     double precision,
  skip_reason   text
);

CREATE TABLE IF NOT EXISTS tour_run_tasks (
  id                     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tour_run_checkpoint_id integer NOT NULL REFERENCES tour_run_checkpoints(id) ON DELETE CASCADE,
  checkpoint_task_id     integer NOT NULL REFERENCES checkpoint_tasks(id) ON DELETE CASCADE,
  status                 text NOT NULL DEFAULT 'pending',
  note                   text,
  completed_at           timestamptz
);

CREATE TABLE IF NOT EXISTS broadcasts (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title            text NOT NULL,
  body             text NOT NULL,
  priority         text NOT NULL DEFAULT 'normal',
  requires_ack     boolean NOT NULL DEFAULT false,
  audience_role    text,
  audience_site_id integer REFERENCES sites(id) ON DELETE SET NULL,
  published_at     timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz,
  created_by       integer REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS broadcast_receipts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  broadcast_id    integer NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at         timestamptz,
  acknowledged_at timestamptz,
  UNIQUE (broadcast_id, user_id)
);

CREATE TABLE IF NOT EXISTS trainings (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title            text NOT NULL,
  description      text,
  video_url        text,
  duration_seconds integer NOT NULL DEFAULT 0,
  required         boolean NOT NULL DEFAULT false,
  due_at           timestamptz,
  audience_role    text,
  created_by       integer REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS training_progress (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  training_id     integer NOT NULL REFERENCES trainings(id) ON DELETE CASCADE,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seconds_watched integer NOT NULL DEFAULT 0,
  completed_at    timestamptz,
  UNIQUE (training_id, user_id)
);

CREATE TABLE IF NOT EXISTS threads (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  subject         text,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz
);

CREATE TABLE IF NOT EXISTS thread_participants (
  thread_id    integer NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  last_read_at timestamptz,
  PRIMARY KEY (thread_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
  id        integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  thread_id integer NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  sender_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body      text NOT NULL,
  sent_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id, sent_at);

CREATE TABLE IF NOT EXISTS flags (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type            text NOT NULL,
  severity        text NOT NULL DEFAULT 'warning',
  occurred_at     timestamptz NOT NULL,
  ref_type        text,
  ref_id          integer,
  detail          jsonb,
  notified_at     timestamptz,
  resolved_at     timestamptz,
  resolved_by     integer REFERENCES users(id) ON DELETE SET NULL,
  resolution_note text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (type, ref_type, ref_id)
);
CREATE INDEX IF NOT EXISTS idx_flags_open ON flags(resolved_at, occurred_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_id   integer REFERENCES users(id) ON DELETE SET NULL,
  action     text NOT NULL,
  entity     text,
  entity_id  integer,
  detail     text,
  ip         text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_log(created_at DESC);

CREATE TABLE IF NOT EXISTS device_tokens (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token        text NOT NULL UNIQUE,
  platform     text,
  device_id    text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_device_user ON device_tokens(user_id);

CREATE TABLE IF NOT EXISTS certifications (
  id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id           integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type              text NOT NULL,
  number            text,
  issuing_authority text,
  issued_on         date,
  expires_on        date,
  document_filename text,
  verified_by       integer REFERENCES users(id) ON DELETE SET NULL,
  verified_at       timestamptz,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_certs_user ON certifications(user_id);
CREATE INDEX IF NOT EXISTS idx_certs_expiry ON certifications(expires_on);

CREATE TABLE IF NOT EXISTS availability (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  weekday    integer NOT NULL,
  start_time text NOT NULL DEFAULT '00:00',
  end_time   text NOT NULL DEFAULT '23:59',
  available  boolean NOT NULL DEFAULT true,
  note       text,
  UNIQUE (user_id, weekday)
);

CREATE TABLE IF NOT EXISTS time_off_requests (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text NOT NULL DEFAULT 'vacation',
  starts_on     date NOT NULL,
  ends_on       date NOT NULL,
  reason        text,
  status        text NOT NULL DEFAULT 'pending',
  decided_by    integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at    timestamptz,
  decision_note text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_timeoff_user ON time_off_requests(user_id, starts_on);
CREATE INDEX IF NOT EXISTS idx_timeoff_status ON time_off_requests(status);

CREATE TABLE IF NOT EXISTS breaks (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  time_entry_id integer NOT NULL REFERENCES time_entries(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type          text NOT NULL DEFAULT 'meal',
  paid          boolean NOT NULL DEFAULT false,
  started_at    timestamptz NOT NULL,
  ended_at      timestamptz,
  minutes       integer,
  start_lat     double precision,
  start_lng     double precision
);
CREATE INDEX IF NOT EXISTS idx_breaks_entry ON breaks(time_entry_id);

CREATE TABLE IF NOT EXISTS panic_alerts (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id   integer REFERENCES time_entries(id) ON DELETE SET NULL,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  triggered_at    timestamptz NOT NULL DEFAULT now(),
  latitude        double precision,
  longitude       double precision,
  accuracy        double precision,
  note            text,
  status          text NOT NULL DEFAULT 'active',
  acknowledged_by integer REFERENCES users(id) ON DELETE SET NULL,
  acknowledged_at timestamptz,
  resolved_at     timestamptz,
  resolution_note text
);
CREATE INDEX IF NOT EXISTS idx_panic_status ON panic_alerts(status, triggered_at);

-- Officers claiming open shifts, and swapping assigned ones between each other.
CREATE TABLE IF NOT EXISTS shift_requests (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind           text NOT NULL,                   -- 'claim' | 'swap' | 'drop'
  shift_id       integer NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  requested_by   integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- For a swap: who is being asked to take it, and what they give back.
  target_user_id integer REFERENCES users(id) ON DELETE CASCADE,
  offered_shift_id integer REFERENCES shifts(id) ON DELETE CASCADE,
  note           text,
  status         text NOT NULL DEFAULT 'pending', -- pending|accepted|declined|approved|denied|cancelled
  decided_by     integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at     timestamptz,
  decision_note  text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_shift_requests_status ON shift_requests(status, created_at);
CREATE INDEX IF NOT EXISTS idx_shift_requests_shift ON shift_requests(shift_id);

-- Read-only client contacts. Scoped to their own sites, and they never see
-- pay, margin or anything about another client.
CREATE TABLE IF NOT EXISTS client_users (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email           text NOT NULL UNIQUE,
  name            text NOT NULL,
  company         text,
  password_hash   text,
  password_salt   text,
  -- Bumped whenever the password changes. A token carries the version it was
  -- issued against, so a reset ends every session the contact had open
  -- elsewhere. A counter rather than a timestamp, because JWT 'iat' is whole
  -- seconds and a reset moments after a sign-in would not be caught.
  token_version   integer NOT NULL DEFAULT 0,
  status          text NOT NULL DEFAULT 'active',
  last_login_at   timestamptz,
  failed_attempts integer NOT NULL DEFAULT 0,
  locked_until    timestamptz,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS client_sites (
  client_user_id integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  site_id        integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  PRIMARY KEY (client_user_id, site_id)
);

-- Single-use links that let a client contact choose their own password.
--
-- Only a hash of the token is stored: a leaked database should not hand
-- somebody a working link. Rows are kept after use so "when did they set it,
-- and from which invitation" stays answerable.
CREATE TABLE IF NOT EXISTS client_password_tokens (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_user_id integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  token_hash     text NOT NULL UNIQUE,
  purpose        text NOT NULL DEFAULT 'invite',   -- invite|reset
  expires_at     timestamptz NOT NULL,
  used_at        timestamptz,
  created_by     integer REFERENCES users(id) ON DELETE SET NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_client_tokens_user ON client_password_tokens(client_user_id);

-- Rate-limit counters.
--
-- In-process counters are per-instance, and a serverless deployment runs many
-- instances, so an attacker simply spreads attempts across them. Counting here
-- means one shared count however many instances are running.
CREATE TABLE IF NOT EXISTS rate_limits (
  key        text PRIMARY KEY,
  count      integer NOT NULL DEFAULT 0,
  reset_at   timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rate_limits_reset ON rate_limits(reset_at);

-- Every message the system decides to send, whether or not a provider is
-- configured to carry it. Without an API key nothing leaves the building and
-- rows land as 'skipped', which is visible in the admin console rather than
-- being a silent black hole.
CREATE TABLE IF NOT EXISTS emails (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  to_email    text NOT NULL,
  to_name     text,
  subject     text NOT NULL,
  body        text NOT NULL,
  kind        text NOT NULL,
  entity      text,
  entity_id   integer,
  status      text NOT NULL DEFAULT 'queued',   -- queued|sent|skipped|failed
  provider    text,
  provider_id text,
  error       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  sent_at     timestamptz
);
CREATE INDEX IF NOT EXISTS idx_emails_created ON emails(created_at DESC);

CREATE TABLE IF NOT EXISTS invoices (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number        text NOT NULL UNIQUE,
  site_id       integer NOT NULL REFERENCES sites(id) ON DELETE RESTRICT,
  period_start  date NOT NULL,
  period_end    date NOT NULL,
  status        text NOT NULL DEFAULT 'draft',   -- draft|sent|paid|void
  subtotal_cents integer NOT NULL DEFAULT 0,
  tax_cents      integer NOT NULL DEFAULT 0,
  total_cents    integer NOT NULL DEFAULT 0,
  -- What the same hours cost us, so margin survives on the record.
  cost_cents     integer NOT NULL DEFAULT 0,
  notes         text,
  issued_at     timestamptz,
  due_on        date,
  paid_at       timestamptz,
  created_by    integer REFERENCES users(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invoices_site ON invoices(site_id, period_start);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id      integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  description     text NOT NULL,
  minutes         integer NOT NULL DEFAULT 0,
  rate_cents      integer NOT NULL DEFAULT 0,
  amount_cents    integer NOT NULL DEFAULT 0,
  cost_cents      integer NOT NULL DEFAULT 0,
  sequence        integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_invoice_lines ON invoice_lines(invoice_id, sequence);

-- Where an officer's device actually was, while they were clocked in.
--
-- Recorded only on duty: the officer app compares an off-duty position with
-- the next post on the device and sends nothing. Each row carries the verdict
-- against the post they were working at the time, so a history reads the same
-- even after a post's geofence is later moved. Pruned by the sweep after
-- RULES.locationRetentionDays.
CREATE TABLE IF NOT EXISTS location_pings (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id integer REFERENCES time_entries(id) ON DELETE CASCADE,
  post_id       integer REFERENCES posts(id) ON DELETE SET NULL,
  recorded_at   timestamptz NOT NULL DEFAULT now(),
  latitude      double precision NOT NULL,
  longitude     double precision NOT NULL,
  accuracy      double precision,
  speed_mps     double precision,
  heading       double precision,
  source        text NOT NULL DEFAULT 'watch',   -- watch|clock_in|clock_out|check_in|break
  geofence      text,                            -- inside|outside|unverified|not_configured
  distance_m    integer
);
CREATE INDEX IF NOT EXISTS idx_pings_user_time ON location_pings(user_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_pings_entry ON location_pings(time_entry_id, recorded_at);
-- For the retention delete, which runs with every sweep.
CREATE INDEX IF NOT EXISTS idx_pings_time ON location_pings(recorded_at);

-- Every change to what a person is paid or billed at, and from when. The
-- current figures stay on users; this is the record of how they got there.
CREATE TABLE IF NOT EXISTS pay_rate_history (
  id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id             integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  effective_on        date NOT NULL,
  employment_type     text NOT NULL,
  pay_type            text NOT NULL,
  pay_rate_cents      integer,
  salary_cents        integer,
  bill_rate_cents     integer,
  overtime_multiplier double precision,
  reason              text,
  changed_by          integer REFERENCES users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pay_history_user ON pay_rate_history(user_id, effective_on DESC);

-- A client asking for more officers than the standing roster: an event, a
-- stretch of extra risk. Raised from the portal, answered by a supervisor who
-- either turns it into open shifts on one of the site's posts or declines it
-- with a reason the client sees.
CREATE TABLE IF NOT EXISTS coverage_requests (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id         integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  client_user_id  integer REFERENCES client_users(id) ON DELETE SET NULL,
  starts_at       timestamptz NOT NULL,
  ends_at         timestamptz NOT NULL,
  officers        integer NOT NULL DEFAULT 1,
  armed           boolean NOT NULL DEFAULT false,
  reason          text NOT NULL,
  status          text NOT NULL DEFAULT 'open',   -- open|scheduled|declined|cancelled
  response        text,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  shifts_created  integer NOT NULL DEFAULT 0,
  handled_by      integer REFERENCES users(id) ON DELETE SET NULL,
  handled_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_coverage_requests_status ON coverage_requests(status, starts_at);
CREATE INDEX IF NOT EXISTS idx_coverage_requests_site ON coverage_requests(site_id, created_at DESC);

-- Payroll close. A pay period is whole payroll weeks, Monday to Sunday, so
-- overtime is never split between two periods. Each officer's hours are
-- approved against a fingerprint of the entries and rates behind them - any
-- later change to either shows as "changed since approved" rather than being
-- silently carried. Closing snapshots every line and locks the entries: a
-- closed period is what was paid, and reads the same forever after.
CREATE TABLE IF NOT EXISTS pay_periods (
  id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  period_start      date NOT NULL,
  period_end        date NOT NULL,
  status            text NOT NULL DEFAULT 'open',   -- open|closed
  notes             text,
  people            integer NOT NULL DEFAULT 0,
  total_minutes     integer NOT NULL DEFAULT 0,
  overtime_minutes  integer NOT NULL DEFAULT 0,
  gross_cents       integer NOT NULL DEFAULT 0,
  w2_cents          integer NOT NULL DEFAULT 0,
  contractor_cents  integer NOT NULL DEFAULT 0,
  closed_at         timestamptz,
  closed_by         integer REFERENCES users(id) ON DELETE SET NULL,
  reopened_at       timestamptz,
  reopen_reason     text,
  created_by        integer REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_pay_periods_start ON pay_periods(period_start);

CREATE TABLE IF NOT EXISTS pay_period_lines (
  id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pay_period_id       integer NOT NULL REFERENCES pay_periods(id) ON DELETE CASCADE,
  user_id             integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fingerprint         text NOT NULL,
  approved_by         integer REFERENCES users(id) ON DELETE SET NULL,
  approved_at         timestamptz NOT NULL DEFAULT now(),
  -- The figures as approved; rewritten with the final figures on close.
  employee_code       text,
  officer             text,
  employment_type     text,
  pay_type            text,
  entries             integer NOT NULL DEFAULT 0,
  minutes             integer NOT NULL DEFAULT 0,
  regular_minutes     integer NOT NULL DEFAULT 0,
  overtime_minutes    integer NOT NULL DEFAULT 0,
  regular_pay_cents   integer,
  overtime_pay_cents  integer,
  gross_cents         integer,
  sites               text,                          -- JSON [{site, minutes}]
  UNIQUE (pay_period_id, user_id)
);
-- What a post pays, when it pays more than the officer standing it earns.
--
-- Separate from pay_rate_history on purpose: that table is a snapshot of a
-- person's record and answers "what was Marcus on in March". This answers
-- "what does the armed night yard pay", which is a property of the post and
-- survives whoever is rostered on it.
--
-- A null user_id is the usual case - the differential belongs to the post and
-- applies to anyone who stands it. Naming a user narrows it to that officer,
-- for the case where one person has negotiated something the post does not
-- pay everyone. Most specific wins: officer-at-post, then post, then the
-- officer's own rate.
CREATE TABLE IF NOT EXISTS post_pay_rates (
  id                  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id             integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id             integer REFERENCES users(id) ON DELETE CASCADE,
  effective_on        date NOT NULL,
  pay_rate_cents      integer NOT NULL,
  overtime_multiplier double precision,
  reason              text,
  changed_by          integer REFERENCES users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_post_pay_rates ON post_pay_rates(post_id, effective_on DESC);

/* --------------------------------------------- keys and equipment ------ */

-- What the company hands an officer at the start of a shift and expects back at
-- the end: radios, key rings, patrol vehicles, and on armed posts the weapon
-- itself. The post orders already tell officers to log a weapon in and out; this
-- is the thing they log it into.
--
-- An item belongs to a site when it lives there - a key ring for that building
-- is no use anywhere else - or to nobody when it travels, like a spare radio.
CREATE TABLE IF NOT EXISTS equipment (
  id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id       integer REFERENCES sites(id) ON DELETE SET NULL,
  category      text NOT NULL,
  label         text NOT NULL,
  identifier    text,
  notes         text,
  -- A key ring or a weapon has to come back before the officer goes home. A
  -- vehicle assigned for a week does not.
  return_by_end_of_shift boolean NOT NULL DEFAULT true,
  -- Only an officer holding a current Class G may sign this out.
  armed_only    boolean NOT NULL DEFAULT false,
  status        text NOT NULL DEFAULT 'available',
  active        boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_equipment_site ON equipment(site_id, status);

-- The chain of custody. One row per issue, closed when it comes back, so the
-- history of who held what is never overwritten - which is the entire point on
-- a post where the item is a firearm or the keys to a building.
CREATE TABLE IF NOT EXISTS equipment_assignments (
  id                integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  equipment_id      integer NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
  user_id           integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  time_entry_id     integer REFERENCES time_entries(id) ON DELETE SET NULL,
  issued_at         timestamptz NOT NULL DEFAULT now(),
  issued_by         integer REFERENCES users(id) ON DELETE SET NULL,
  issued_condition  text,
  issued_note       text,
  returned_at       timestamptz,
  returned_to       integer REFERENCES users(id) ON DELETE SET NULL,
  returned_condition text,
  returned_note     text
);
CREATE INDEX IF NOT EXISTS idx_equip_assign_open ON equipment_assignments(equipment_id, returned_at);
CREATE INDEX IF NOT EXISTS idx_equip_assign_user ON equipment_assignments(user_id, returned_at);

/* ------------------------------------------------- the post's own logs --- */

-- Everyone who comes through a post: signed in by the officer on duty, signed
-- out when they leave. Kept against the site as well as the post, because the
-- question a client asks is "who was in my building", not "at which desk".
CREATE TABLE IF NOT EXISTS visitor_log (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id          integer REFERENCES posts(id) ON DELETE SET NULL,
  full_name        text NOT NULL,
  company          text,
  purpose          text NOT NULL,
  host             text,
  kind             text NOT NULL DEFAULT 'visitor',   -- visitor|contractor|delivery|vendor|other
  vehicle_plate    text,
  vehicle_desc     text,
  badge_number     text,
  arrived_at       timestamptz NOT NULL DEFAULT now(),
  departed_at      timestamptz,
  logged_by        integer REFERENCES users(id) ON DELETE SET NULL,
  departed_by      integer REFERENCES users(id) ON DELETE SET NULL,
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_visitor_log_site ON visitor_log(site_id, arrived_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitor_log_open ON visitor_log(site_id, departed_at);

-- What one shift tells the next: the gate that sticks, the tenant expecting a
-- delivery, the car that has been parked in the fire lane since Tuesday. The
-- next officer on the post acknowledges each note, so a supervisor can see it
-- was read rather than hope it was.
CREATE TABLE IF NOT EXISTS passdown_notes (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id          integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id        integer REFERENCES users(id) ON DELETE SET NULL,
  time_entry_id    integer REFERENCES time_entries(id) ON DELETE SET NULL,
  body             text NOT NULL,
  priority         text NOT NULL DEFAULT 'normal',    -- normal|important
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_passdown_post ON passdown_notes(post_id, created_at DESC);

-- People who are not to be let in: trespassed, barred by the client, a
-- former employee. Kept per site, or company-wide when site_id is NULL. The
-- visitor log checks every sign-in against it, so the officer is told at the
-- desk rather than finding out afterwards.
CREATE TABLE IF NOT EXISTS watchlist (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id         integer REFERENCES sites(id) ON DELETE CASCADE,
  full_name       text NOT NULL,
  aliases         text,
  description     text,
  vehicle_plate   text,
  reason          text NOT NULL,
  action          text NOT NULL DEFAULT 'deny_entry',  -- deny_entry|call_police|notify_supervisor|escort
  risk            text NOT NULL DEFAULT 'medium',      -- low|medium|high
  expires_on      date,
  active          boolean NOT NULL DEFAULT true,
  added_by        integer REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_watchlist_site ON watchlist(site_id, active);

-- Parking and vehicle enforcement: the fire lane, the unpermitted car, the
-- truck left on the dock. Keyed by plate so a repeat offender shows up as one,
-- whichever officer or site logged the earlier ones.
CREATE TABLE IF NOT EXISTS vehicle_violations (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id         integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  plate           text NOT NULL,
  plate_state     text,
  vehicle_desc    text,
  location_text   text,
  violation       text NOT NULL,                       -- fire_lane|no_permit|accessible|blocking|abandoned|reserved|other
  action          text NOT NULL DEFAULT 'warning',     -- warning|tagged|booted|towed
  notes           text,
  logged_by       integer REFERENCES users(id) ON DELETE SET NULL,
  occurred_at     timestamptz NOT NULL DEFAULT now(),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_violations_plate ON vehicle_violations(plate, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_violations_site ON vehicle_violations(site_id, occurred_at DESC);

-- A visitor signed in despite a watchlist match carries the entry it matched,
-- so the log shows it and the supervisor can follow it up.
ALTER TABLE visitor_log ADD COLUMN IF NOT EXISTS watchlist_id integer REFERENCES watchlist(id) ON DELETE SET NULL;

-- What each client contact wants by email. Serious incident alerts are on
-- unless they turn them off; the daily report is opt-in.
ALTER TABLE client_users ADD COLUMN IF NOT EXISTS notify_serious_incidents boolean NOT NULL DEFAULT true;
ALTER TABLE client_users ADD COLUMN IF NOT EXISTS notify_daily_report boolean NOT NULL DEFAULT false;
-- Set when the client has been told about a serious incident, so a later
-- review that keeps it serious does not tell them twice.
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS client_notified_at timestamptz;

-- What the client reads about a supervisor's visit. The visit's own notes are
-- about the officer (coaching, a missing patch) and stay with us.
ALTER TABLE supervisor_visits ADD COLUMN IF NOT EXISTS client_note text;
-- Shift confirmations. A confirmation is for one officer, one post and one
-- set of times: confirmed_key records which, so moving or reassigning the
-- shift leaves it unconfirmed without every update path having to clear it.
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS confirmed_at timestamptz;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS confirmed_by integer REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS confirm_method text;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS confirm_note text;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS confirmed_key text;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS reminded_key text;
CREATE INDEX IF NOT EXISTS idx_supervisor_visits_site ON supervisor_visits(site_id, visited_at);

-- What is being done about an incident: a corrective action with an owner
-- and a due date. The client sees the ones marked client-visible, without
-- who owns them.
CREATE TABLE IF NOT EXISTS incident_actions (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  incident_id    integer NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  title          text NOT NULL,
  owner_id       integer REFERENCES users(id) ON DELETE SET NULL,
  due_on         date,
  status         text NOT NULL DEFAULT 'open',   -- open|done
  client_visible boolean NOT NULL DEFAULT true,
  done_note      text,
  done_at        timestamptz,
  done_by        integer REFERENCES users(id) ON DELETE SET NULL,
  created_by     integer REFERENCES users(id) ON DELETE SET NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_incident_actions_incident ON incident_actions(incident_id);
CREATE INDEX IF NOT EXISTS idx_incident_actions_open ON incident_actions(status, due_on);

-- Set when the client was told a shared follow-up was done, so reopening and
-- closing it again does not email them twice.
ALTER TABLE incident_actions ADD COLUMN IF NOT EXISTS client_notified_at timestamptz;

-- A client's question about an issued invoice, optionally about one line.
-- Answered by the office; the answer reaches the client in the portal and by
-- email. An invoice cannot have more than three waiting at once.
CREATE TABLE IF NOT EXISTS invoice_queries (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  invoice_id     integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  line_id        integer REFERENCES invoice_lines(id) ON DELETE SET NULL,
  client_user_id integer REFERENCES client_users(id) ON DELETE SET NULL,
  question       text NOT NULL,
  status         text NOT NULL DEFAULT 'open',   -- open|answered
  answer         text,
  answered_by    integer REFERENCES users(id) ON DELETE SET NULL,
  answered_at    timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invoice_queries_invoice ON invoice_queries(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_queries_status ON invoice_queries(status);

-- A notice from us to client contacts: a hurricane plan, holiday coverage, a
-- change of account manager. To every property or to chosen ones, shown in
-- the portal between its start and end, and optionally emailed when posted.
CREATE TABLE IF NOT EXISTS client_notices (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title        text NOT NULL,
  body         text NOT NULL,
  level        text NOT NULL DEFAULT 'info',   -- info|important|urgent
  all_sites    boolean NOT NULL DEFAULT false,
  starts_at    timestamptz NOT NULL DEFAULT now(),
  ends_at      timestamptz,
  emailed_at   timestamptz,
  withdrawn_at timestamptz,
  created_by   integer REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS client_notice_sites (
  notice_id integer NOT NULL REFERENCES client_notices(id) ON DELETE CASCADE,
  site_id   integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  PRIMARY KEY (notice_id, site_id)
);
CREATE TABLE IF NOT EXISTS client_notice_reads (
  notice_id      integer NOT NULL REFERENCES client_notices(id) ON DELETE CASCADE,
  client_user_id integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  read_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (notice_id, client_user_id)
);

-- People who want to work for us, from the website form or entered by the
-- office. Kept apart from users: an applicant has no code, no PIN and no
-- access until they are hired, when a users row is made for them.
CREATE TABLE IF NOT EXISTS applicants (
  id                 integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name         text NOT NULL,
  last_name          text NOT NULL,
  email              text NOT NULL,
  phone              text NOT NULL,
  city               text,
  licence_class      text NOT NULL DEFAULT 'none',  -- none|D|G|DG
  licence_number     text,
  licence_expires_on date,
  experience         text,
  availability       text,
  source             text NOT NULL DEFAULT 'website',
  referred_by        text,
  stage              text NOT NULL DEFAULT 'applied',
  stage_changed_at   timestamptz NOT NULL DEFAULT now(),
  rejected_reason    text,
  hired_user_id      integer REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_applicants_stage ON applicants(stage, stage_changed_at);
CREATE INDEX IF NOT EXISTS idx_applicants_email ON applicants(lower(email));
CREATE TABLE IF NOT EXISTS applicant_checks (
  applicant_id integer NOT NULL REFERENCES applicants(id) ON DELETE CASCADE,
  key          text NOT NULL,
  done_at      timestamptz NOT NULL DEFAULT now(),
  done_by      integer REFERENCES users(id) ON DELETE SET NULL,
  note         text,
  PRIMARY KEY (applicant_id, key)
);
CREATE TABLE IF NOT EXISTS applicant_notes (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  applicant_id integer NOT NULL REFERENCES applicants(id) ON DELETE CASCADE,
  author_id    integer REFERENCES users(id) ON DELETE SET NULL,
  body         text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);

/* ------------------------------------------------ service agreements --- */

-- What each property pays us for: hours of guarding a week, and when the
-- agreement runs out. One current agreement per site; the notes are ours.
CREATE TABLE IF NOT EXISTS site_agreements (
  site_id       integer PRIMARY KEY REFERENCES sites(id) ON DELETE CASCADE,
  weekly_hours  numeric(7,1) NOT NULL,
  starts_on     date,
  ends_on       date,
  notice_days   integer NOT NULL DEFAULT 60,
  auto_renew    boolean NOT NULL DEFAULT false,
  notes         text,
  updated_by    integer REFERENCES users(id) ON DELETE SET NULL,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

/* ------------------------------------------------ time corrections ----- */

-- An officer's request to fix one of their punches. Approving it applies the
-- change through the same path as an administrator's correction, so the
-- original times are kept on the entry and a closed pay period is refused.
CREATE TABLE IF NOT EXISTS time_corrections (
  id                    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  time_entry_id         integer NOT NULL REFERENCES time_entries(id) ON DELETE CASCADE,
  user_id               integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  proposed_clock_in_at  timestamptz,
  proposed_clock_out_at timestamptz,
  recorded_clock_in_at  timestamptz NOT NULL,            -- what the entry said when they asked
  recorded_clock_out_at timestamptz,
  reason                text NOT NULL,
  status                text NOT NULL DEFAULT 'pending', -- pending|approved|declined|withdrawn
  decided_by            integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at            timestamptz,
  decision_note         text,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_time_corrections_status ON time_corrections(status, created_at);
CREATE INDEX IF NOT EXISTS idx_time_corrections_entry ON time_corrections(time_entry_id);

/* --------------------------------------------- calls for service ------ */

-- Something at a property that needs an officer now. The timestamps are the
-- point: call to sent, sent to acknowledged, call to on scene, all measured.
CREATE TABLE IF NOT EXISTS service_calls (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id         integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  call_type       text NOT NULL,
  priority        integer NOT NULL DEFAULT 3,
  location        text,                                   -- where on the property
  description     text NOT NULL,
  caller_name     text,
  caller_phone    text,
  source          text NOT NULL DEFAULT 'office',         -- office|client
  client_user_id  integer REFERENCES client_users(id) ON DELETE SET NULL,
  created_by      integer REFERENCES users(id) ON DELETE SET NULL,
  status          text NOT NULL DEFAULT 'open',           -- open|assigned|en_route|on_scene|cleared|cancelled
  assigned_to     integer REFERENCES users(id) ON DELETE SET NULL,
  assigned_by     integer REFERENCES users(id) ON DELETE SET NULL,
  assigned_at     timestamptz,
  acknowledged_at timestamptz,
  arrived_at      timestamptz,
  cleared_at      timestamptz,
  cleared_by      integer REFERENCES users(id) ON DELETE SET NULL,
  disposition     text,
  outcome         text,                                   -- what the officer found; the client reads it
  incident_id     integer REFERENCES incidents(id) ON DELETE SET NULL,
  cancelled_at    timestamptz,
  cancel_reason   text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_service_calls_status ON service_calls(status, created_at);
CREATE INDEX IF NOT EXISTS idx_service_calls_site ON service_calls(site_id, created_at);
CREATE INDEX IF NOT EXISTS idx_service_calls_officer ON service_calls(assigned_to, status);

-- Everything that happened to a call, in order: raised, sent, turned back,
-- acknowledged, on scene, cleared. Staff-only; clients see the timestamps.
CREATE TABLE IF NOT EXISTS service_call_events (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  call_id        integer NOT NULL REFERENCES service_calls(id) ON DELETE CASCADE,
  kind           text NOT NULL,
  user_id        integer REFERENCES users(id) ON DELETE SET NULL,
  client_user_id integer REFERENCES client_users(id) ON DELETE SET NULL,
  note           text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_service_call_events ON service_call_events(call_id, created_at);

-- One daily report email per contact, site and day, however often the sweep runs.
CREATE TABLE IF NOT EXISTS client_digests (
  client_user_id integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  site_id        integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  day            date NOT NULL,
  sent_at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (client_user_id, site_id, day)
);

-- The officer's running log through the shift: rounds walked, doors found
-- open, alarms answered. The backbone of a daily activity report, and read by
-- the client unless the officer marks an entry internal.
CREATE TABLE IF NOT EXISTS activity_entries (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id         integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id         integer REFERENCES posts(id) ON DELETE SET NULL,
  user_id         integer REFERENCES users(id) ON DELETE SET NULL,
  time_entry_id   integer REFERENCES time_entries(id) ON DELETE SET NULL,
  category        text NOT NULL DEFAULT 'observation',  -- patrol|observation|access|alarm|safety|customer_service|other
  body            text NOT NULL,
  client_visible  boolean NOT NULL DEFAULT true,
  occurred_at     timestamptz NOT NULL DEFAULT now(),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_activity_site ON activity_entries(site_id, occurred_at DESC);

-- Things wrong with the building that officers find and the client has to
-- fix: a light out in the garage, a door that will not latch, a leak. The
-- client acknowledges and closes them from the portal, so both sides see the
-- same list rather than an email thread.
CREATE TABLE IF NOT EXISTS site_issues (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id          integer REFERENCES posts(id) ON DELETE SET NULL,
  reported_by      integer REFERENCES users(id) ON DELETE SET NULL,
  category         text NOT NULL,                        -- lighting|door_lock|leak|damage|hazard|cleanliness|equipment|other
  priority         text NOT NULL DEFAULT 'normal',       -- low|normal|urgent
  location_text    text,
  description      text NOT NULL,
  status           text NOT NULL DEFAULT 'open',         -- open|acknowledged|fixed
  client_note      text,
  acknowledged_at  timestamptz,
  fixed_at         timestamptz,
  closed_by_client integer REFERENCES client_users(id) ON DELETE SET NULL,
  closed_by_staff  integer REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_site_issues_site ON site_issues(site_id, status, created_at DESC);

-- Property found on site, where it is kept, and how it left: back to its
-- owner (who, and who handed it over) or disposed of after the holding period.
CREATE TABLE IF NOT EXISTS lost_found (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  post_id          integer REFERENCES posts(id) ON DELETE SET NULL,
  found_by         integer REFERENCES users(id) ON DELETE SET NULL,
  description      text NOT NULL,
  category         text NOT NULL DEFAULT 'other',        -- phone|wallet|keys|bag|id|clothing|jewelry|other
  found_location   text,
  stored_location  text,
  found_at         timestamptz NOT NULL DEFAULT now(),
  status           text NOT NULL DEFAULT 'held',         -- held|returned|disposed
  returned_to      text,
  returned_contact text,
  closed_at        timestamptz,
  closed_by        integer REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_lost_found_site ON lost_found(site_id, status, found_at DESC);

-- Who the officer on post calls: the property manager, maintenance, the
-- alarm company, the police non-emergency line. Kept by supervisors and by
-- the client, who knows their own people best.
CREATE TABLE IF NOT EXISTS site_contacts (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name             text NOT NULL,
  role             text NOT NULL,
  phone            text,
  email            text,
  notes            text,
  after_hours      boolean NOT NULL DEFAULT false,
  sort             integer NOT NULL DEFAULT 0,
  added_by_user    integer REFERENCES users(id) ON DELETE SET NULL,
  added_by_client  integer REFERENCES client_users(id) ON DELETE SET NULL,
  updated_at       timestamptz NOT NULL DEFAULT now(),
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_site_contacts_site ON site_contacts(site_id, sort);

-- How the client rates the service, once a month per property. Changing it
-- within the month replaces the rating rather than piling up duplicates; a
-- manager's reply goes back to the client in the portal.
CREATE TABLE IF NOT EXISTS client_feedback (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_user_id   integer NOT NULL REFERENCES client_users(id) ON DELETE CASCADE,
  site_id          integer NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  period           text NOT NULL,                        -- YYYY-MM
  rating           integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment          text,
  response         text,
  responded_by     integer REFERENCES users(id) ON DELETE SET NULL,
  responded_at     timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (client_user_id, site_id, period)
);
CREATE INDEX IF NOT EXISTS idx_client_feedback_period ON client_feedback(period, site_id);

-- Post orders: the standing instructions for a post, versioned. A change
-- is a new version, never an edit in place, so "what did the orders say on
-- the night of the incident" always has an answer - and every officer who
-- works the post has to acknowledge the version in force.
CREATE TABLE IF NOT EXISTS post_orders (
  id           integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id      integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  version      integer NOT NULL,
  body         text NOT NULL,
  change_note  text,
  created_by   integer REFERENCES users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (post_id, version)
);

CREATE TABLE IF NOT EXISTS post_order_acks (
  post_order_id integer NOT NULL REFERENCES post_orders(id) ON DELETE CASCADE,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  acked_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (post_order_id, user_id)
);

-- A client asking for a change to a post's orders. A supervisor applies it
-- (as a new version of the orders) or declines it with a reply; either way
-- the client sees the outcome in the portal and by email.
CREATE TABLE IF NOT EXISTS post_order_requests (
  id               integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id          integer NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  client_user_id   integer REFERENCES client_users(id) ON DELETE SET NULL,
  body             text NOT NULL,
  status           text NOT NULL DEFAULT 'open',  -- open|applied|declined|withdrawn
  response         text,
  applied_order_id integer REFERENCES post_orders(id) ON DELETE SET NULL,
  resolved_by      integer REFERENCES users(id) ON DELETE SET NULL,
  resolved_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_post_order_requests_post ON post_order_requests(post_id, status);

-- Which items in a supervisor's alert inbox they have read. Alerts are
-- worked out from the records themselves; only the read marks are stored.
CREATE TABLE IF NOT EXISTS alert_reads (
  user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  alert_key  text NOT NULL,
  read_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, alert_key)
);

CREATE TABLE IF NOT EXISTS passdown_acks (
  note_id          integer NOT NULL REFERENCES passdown_notes(id) ON DELETE CASCADE,
  user_id          integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  acked_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (note_id, user_id)
);

/* ------------------------------------------------- patrol vehicles --- */

-- A vehicle is an equipment item with an odometer. The last reading is kept on
-- the item so a new one can be checked against it; the readings themselves
-- live in the inspections.
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS odometer integer;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS service_due_miles integer;

-- Walk-round checks at the start and end of a stretch with the vehicle, and
-- the service record, in one log: each is an odometer reading with a time and
-- a name, which is what the mileage is worked out from.
CREATE TABLE IF NOT EXISTS vehicle_inspections (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  equipment_id   integer NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
  user_id        integer REFERENCES users(id) ON DELETE SET NULL,
  assignment_id  integer REFERENCES equipment_assignments(id) ON DELETE SET NULL,
  kind           text NOT NULL,              -- start|end|service
  odometer       integer NOT NULL,
  fuel_level     integer,                    -- quarters of a tank, 0-4
  checks         text,                       -- JSON {item: 'ok'|'fail'}
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vehicle_inspections ON vehicle_inspections(equipment_id, created_at);
CREATE INDEX IF NOT EXISTS idx_vehicle_inspections_assignment ON vehicle_inspections(assignment_id, kind);

-- Something wrong with a vehicle, from a failed check, until somebody fixes it.
-- A critical one takes the vehicle off the road.
CREATE TABLE IF NOT EXISTS vehicle_defects (
  id             integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  equipment_id   integer NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
  inspection_id  integer REFERENCES vehicle_inspections(id) ON DELETE SET NULL,
  item           text NOT NULL,
  critical       boolean NOT NULL DEFAULT false,
  note           text,
  reported_by    integer REFERENCES users(id) ON DELETE SET NULL,
  reported_at    timestamptz NOT NULL DEFAULT now(),
  resolved_at    timestamptz,
  resolved_by    integer REFERENCES users(id) ON DELETE SET NULL,
  resolution     text
);
CREATE INDEX IF NOT EXISTS idx_vehicle_defects_open ON vehicle_defects(equipment_id, resolved_at);

/* ---------------------------------------------------- expense claims --- */

-- Money an officer spent on the job and claims back: mileage in their own
-- vehicle, parking, tolls, supplies. An administrator approves it, and the
-- payroll close that follows pays it, recording which period did.
CREATE TABLE IF NOT EXISTS expense_claims (
  id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id         integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  site_id         integer REFERENCES sites(id) ON DELETE SET NULL,
  category        text NOT NULL,
  incurred_on     date NOT NULL,
  miles           numeric(7,1),
  amount_cents    integer NOT NULL,
  description     text NOT NULL,
  receipt_filename text,
  receipt_url     text,
  receipt_type    text,
  status          text NOT NULL DEFAULT 'pending',   -- pending|approved|declined|withdrawn|paid
  decided_by      integer REFERENCES users(id) ON DELETE SET NULL,
  decided_at      timestamptz,
  decision_note   text,
  pay_period_id   integer REFERENCES pay_periods(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_expense_claims_user ON expense_claims(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_expense_claims_status ON expense_claims(status, incurred_on);

-- Paid time off: every hour earned, used or adjusted. The balance is the sum.
CREATE TABLE IF NOT EXISTS pto_ledger (
  id                   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id              integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind                 text NOT NULL,                     -- accrual | used | adjustment
  hours                numeric(7,2) NOT NULL,              -- negative when used
  pay_period_id        integer REFERENCES pay_periods(id) ON DELETE CASCADE,
  time_off_request_id  integer REFERENCES time_off_requests(id) ON DELETE CASCADE,
  note                 text,
  created_by           integer REFERENCES users(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pto_user ON pto_ledger(user_id, created_at);
-- A time-off request can be paid from the balance; the close that pays it is recorded.
ALTER TABLE time_off_requests ADD COLUMN IF NOT EXISTS pto_hours numeric(6,2);
ALTER TABLE time_off_requests ADD COLUMN IF NOT EXISTS pto_pay_cents integer;
ALTER TABLE time_off_requests ADD COLUMN IF NOT EXISTS pto_paid_period_id integer REFERENCES pay_periods(id) ON DELETE SET NULL;
`;
